name: dart2cloud
description: Tools for deploying dart functions in cloud
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive: ^3.3.0
  args: ^2.3.0
  dio: ^4.0.6
  json_annotation: ^4.5.0
  node_interop: ^2.1.0
  node_preamble: ^2.0.1

dev_dependencies:
  dart_code_metrics: ^4.7.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.8
